### PR TITLE
Updated Tracking (GTM)

### PR DESCRIPTION
**Pull request by Shipow**

### CODE REVIEW

**Comment by Jerska** [comment]
Will close to add it to `algoliasearch-zendesk` instead. This repo just holds the generated version.

**Comment by Jerska** [comment]
So basically, we're tracking way less now, right @Shipow ?

**Comment by Jerska** [comment]
Even HotJar btw ? Seemed pretty useful to understand the interactions on the website.

**Comment by Jerska** [comment]
cf https://github.com/algolia/algoliasearch-zendesk/commit/cb26c802c1964b39dfcc366c39c808fbc57449d1

**Comment by Shipow** [comment]
No @Jerskouille every other tags are fired by GTM, we'll actually track more.

**Pull request closed without merging**
